/*
Copyright AppsCode Inc. and Contributors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1alpha1 "kubeops.dev/falco-ui-server/apis/falco/v1alpha1"
	scheme "kubeops.dev/falco-ui-server/client/clientset/versioned/scheme"
)

// RuntimeEventsGetter has a method to return a RuntimeEventInterface.
// A group's client should implement this interface.
type RuntimeEventsGetter interface {
	RuntimeEvents() RuntimeEventInterface
}

// RuntimeEventInterface has methods to work with RuntimeEvent resources.
type RuntimeEventInterface interface {
	Create(ctx context.Context, runtimeEvent *v1alpha1.RuntimeEvent, opts v1.CreateOptions) (*v1alpha1.RuntimeEvent, error)
	Update(ctx context.Context, runtimeEvent *v1alpha1.RuntimeEvent, opts v1.UpdateOptions) (*v1alpha1.RuntimeEvent, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.RuntimeEvent, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.RuntimeEventList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.RuntimeEvent, err error)
	RuntimeEventExpansion
}

// runtimeEvents implements RuntimeEventInterface
type runtimeEvents struct {
	client rest.Interface
}

// newRuntimeEvents returns a RuntimeEvents
func newRuntimeEvents(c *FalcoV1alpha1Client) *runtimeEvents {
	return &runtimeEvents{
		client: c.RESTClient(),
	}
}

// Get takes name of the runtimeEvent, and returns the corresponding runtimeEvent object, and an error if there is any.
func (c *runtimeEvents) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.RuntimeEvent, err error) {
	result = &v1alpha1.RuntimeEvent{}
	err = c.client.Get().
		Resource("runtimeevents").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of RuntimeEvents that match those selectors.
func (c *runtimeEvents) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.RuntimeEventList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.RuntimeEventList{}
	err = c.client.Get().
		Resource("runtimeevents").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested runtimeEvents.
func (c *runtimeEvents) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("runtimeevents").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a runtimeEvent and creates it.  Returns the server's representation of the runtimeEvent, and an error, if there is any.
func (c *runtimeEvents) Create(ctx context.Context, runtimeEvent *v1alpha1.RuntimeEvent, opts v1.CreateOptions) (result *v1alpha1.RuntimeEvent, err error) {
	result = &v1alpha1.RuntimeEvent{}
	err = c.client.Post().
		Resource("runtimeevents").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(runtimeEvent).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a runtimeEvent and updates it. Returns the server's representation of the runtimeEvent, and an error, if there is any.
func (c *runtimeEvents) Update(ctx context.Context, runtimeEvent *v1alpha1.RuntimeEvent, opts v1.UpdateOptions) (result *v1alpha1.RuntimeEvent, err error) {
	result = &v1alpha1.RuntimeEvent{}
	err = c.client.Put().
		Resource("runtimeevents").
		Name(runtimeEvent.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(runtimeEvent).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the runtimeEvent and deletes it. Returns an error if one occurs.
func (c *runtimeEvents) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("runtimeevents").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *runtimeEvents) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("runtimeevents").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched runtimeEvent.
func (c *runtimeEvents) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.RuntimeEvent, err error) {
	result = &v1alpha1.RuntimeEvent{}
	err = c.client.Patch(pt).
		Resource("runtimeevents").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
