//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright AppsCode Inc. and Contributors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	falco "kubeops.dev/falco-ui-server/apis/falco"

	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*RuntimeEvent)(nil), (*falco.RuntimeEvent)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RuntimeEvent_To_falco_RuntimeEvent(a.(*RuntimeEvent), b.(*falco.RuntimeEvent), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*falco.RuntimeEvent)(nil), (*RuntimeEvent)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_falco_RuntimeEvent_To_v1alpha1_RuntimeEvent(a.(*falco.RuntimeEvent), b.(*RuntimeEvent), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RuntimeEventList)(nil), (*falco.RuntimeEventList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RuntimeEventList_To_falco_RuntimeEventList(a.(*RuntimeEventList), b.(*falco.RuntimeEventList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*falco.RuntimeEventList)(nil), (*RuntimeEventList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_falco_RuntimeEventList_To_v1alpha1_RuntimeEventList(a.(*falco.RuntimeEventList), b.(*RuntimeEventList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RuntimeEventSpec)(nil), (*falco.RuntimeEventSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RuntimeEventSpec_To_falco_RuntimeEventSpec(a.(*RuntimeEventSpec), b.(*falco.RuntimeEventSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*falco.RuntimeEventSpec)(nil), (*RuntimeEventSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_falco_RuntimeEventSpec_To_v1alpha1_RuntimeEventSpec(a.(*falco.RuntimeEventSpec), b.(*RuntimeEventSpec), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_RuntimeEvent_To_falco_RuntimeEvent(in *RuntimeEvent, out *falco.RuntimeEvent, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_RuntimeEventSpec_To_falco_RuntimeEventSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_RuntimeEvent_To_falco_RuntimeEvent is an autogenerated conversion function.
func Convert_v1alpha1_RuntimeEvent_To_falco_RuntimeEvent(in *RuntimeEvent, out *falco.RuntimeEvent, s conversion.Scope) error {
	return autoConvert_v1alpha1_RuntimeEvent_To_falco_RuntimeEvent(in, out, s)
}

func autoConvert_falco_RuntimeEvent_To_v1alpha1_RuntimeEvent(in *falco.RuntimeEvent, out *RuntimeEvent, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_falco_RuntimeEventSpec_To_v1alpha1_RuntimeEventSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_falco_RuntimeEvent_To_v1alpha1_RuntimeEvent is an autogenerated conversion function.
func Convert_falco_RuntimeEvent_To_v1alpha1_RuntimeEvent(in *falco.RuntimeEvent, out *RuntimeEvent, s conversion.Scope) error {
	return autoConvert_falco_RuntimeEvent_To_v1alpha1_RuntimeEvent(in, out, s)
}

func autoConvert_v1alpha1_RuntimeEventList_To_falco_RuntimeEventList(in *RuntimeEventList, out *falco.RuntimeEventList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]falco.RuntimeEvent)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_RuntimeEventList_To_falco_RuntimeEventList is an autogenerated conversion function.
func Convert_v1alpha1_RuntimeEventList_To_falco_RuntimeEventList(in *RuntimeEventList, out *falco.RuntimeEventList, s conversion.Scope) error {
	return autoConvert_v1alpha1_RuntimeEventList_To_falco_RuntimeEventList(in, out, s)
}

func autoConvert_falco_RuntimeEventList_To_v1alpha1_RuntimeEventList(in *falco.RuntimeEventList, out *RuntimeEventList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]RuntimeEvent)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_falco_RuntimeEventList_To_v1alpha1_RuntimeEventList is an autogenerated conversion function.
func Convert_falco_RuntimeEventList_To_v1alpha1_RuntimeEventList(in *falco.RuntimeEventList, out *RuntimeEventList, s conversion.Scope) error {
	return autoConvert_falco_RuntimeEventList_To_v1alpha1_RuntimeEventList(in, out, s)
}

func autoConvert_v1alpha1_RuntimeEventSpec_To_falco_RuntimeEventSpec(in *RuntimeEventSpec, out *falco.RuntimeEventSpec, s conversion.Scope) error {
	out.UUID = in.UUID
	out.Output = in.Output
	out.Priority = in.Priority
	out.Rule = in.Rule
	out.Time = in.Time
	out.OutputFields = in.OutputFields
	out.Source = in.Source
	out.Tags = *(*[]string)(unsafe.Pointer(&in.Tags))
	out.Hostname = in.Hostname
	out.Nodename = in.Nodename
	return nil
}

// Convert_v1alpha1_RuntimeEventSpec_To_falco_RuntimeEventSpec is an autogenerated conversion function.
func Convert_v1alpha1_RuntimeEventSpec_To_falco_RuntimeEventSpec(in *RuntimeEventSpec, out *falco.RuntimeEventSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_RuntimeEventSpec_To_falco_RuntimeEventSpec(in, out, s)
}

func autoConvert_falco_RuntimeEventSpec_To_v1alpha1_RuntimeEventSpec(in *falco.RuntimeEventSpec, out *RuntimeEventSpec, s conversion.Scope) error {
	out.UUID = in.UUID
	out.Output = in.Output
	out.Priority = in.Priority
	out.Rule = in.Rule
	out.Time = in.Time
	out.OutputFields = in.OutputFields
	out.Source = in.Source
	out.Tags = *(*[]string)(unsafe.Pointer(&in.Tags))
	out.Hostname = in.Hostname
	out.Nodename = in.Nodename
	return nil
}

// Convert_falco_RuntimeEventSpec_To_v1alpha1_RuntimeEventSpec is an autogenerated conversion function.
func Convert_falco_RuntimeEventSpec_To_v1alpha1_RuntimeEventSpec(in *falco.RuntimeEventSpec, out *RuntimeEventSpec, s conversion.Scope) error {
	return autoConvert_falco_RuntimeEventSpec_To_v1alpha1_RuntimeEventSpec(in, out, s)
}
