/*
Copyright AppsCode Inc. and Contributors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
	v1alpha1 "kubeops.dev/falco-ui-server/apis/falco/v1alpha1"
)

// FalcoEventLister helps list FalcoEvents.
// All objects returned here must be treated as read-only.
type FalcoEventLister interface {
	// List lists all FalcoEvents in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.FalcoEvent, err error)
	// Get retrieves the FalcoEvent from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.FalcoEvent, error)
	FalcoEventListerExpansion
}

// falcoEventLister implements the FalcoEventLister interface.
type falcoEventLister struct {
	indexer cache.Indexer
}

// NewFalcoEventLister returns a new FalcoEventLister.
func NewFalcoEventLister(indexer cache.Indexer) FalcoEventLister {
	return &falcoEventLister{indexer: indexer}
}

// List lists all FalcoEvents in the indexer.
func (s *falcoEventLister) List(selector labels.Selector) (ret []*v1alpha1.FalcoEvent, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.FalcoEvent))
	})
	return ret, err
}

// Get retrieves the FalcoEvent from the index for a given name.
func (s *falcoEventLister) Get(name string) (*v1alpha1.FalcoEvent, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("falcoevent"), name)
	}
	return obj.(*v1alpha1.FalcoEvent), nil
}
