/*
Copyright AppsCode Inc. and Contributors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
	v1alpha1 "kubeops.dev/falco-ui-server/apis/falco/v1alpha1"
)

// RuntimeEventLister helps list RuntimeEvents.
// All objects returned here must be treated as read-only.
type RuntimeEventLister interface {
	// List lists all RuntimeEvents in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.RuntimeEvent, err error)
	// Get retrieves the RuntimeEvent from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.RuntimeEvent, error)
	RuntimeEventListerExpansion
}

// runtimeEventLister implements the RuntimeEventLister interface.
type runtimeEventLister struct {
	indexer cache.Indexer
}

// NewRuntimeEventLister returns a new RuntimeEventLister.
func NewRuntimeEventLister(indexer cache.Indexer) RuntimeEventLister {
	return &runtimeEventLister{indexer: indexer}
}

// List lists all RuntimeEvents in the indexer.
func (s *runtimeEventLister) List(selector labels.Selector) (ret []*v1alpha1.RuntimeEvent, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.RuntimeEvent))
	})
	return ret, err
}

// Get retrieves the RuntimeEvent from the index for a given name.
func (s *runtimeEventLister) Get(name string) (*v1alpha1.RuntimeEvent, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("runtimeevent"), name)
	}
	return obj.(*v1alpha1.RuntimeEvent), nil
}
