
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: runtimeevents.falco.appscode.com
spec:
  group: falco.appscode.com
  names:
    kind: RuntimeEvent
    listKind: RuntimeEventList
    plural: runtimeevents
    singular: runtimeevent
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: Spec describes the attributes for the Image Scan SingleReport
            properties:
              hostname:
                type: string
              output:
                type: string
              outputFields:
                x-kubernetes-preserve-unknown-fields: true
              priority:
                type: string
              rule:
                type: string
              source:
                type: string
              tags:
                items:
                  type: string
                type: array
              time:
                format: date-time
                type: string
              uuid:
                type: string
            required:
            - output
            - outputFields
            - priority
            - rule
            - source
            - time
            type: object
          status:
            description: Status holds all the SingleReport-related details of the
              specified image
            type: object
        type: object
    served: true
    storage: true
