/*
Copyright AppsCode Inc. and Contributors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "kubeops.dev/falco-ui-server/apis/falco/v1alpha1"
)

// FakeRuntimeEvents implements RuntimeEventInterface
type FakeRuntimeEvents struct {
	Fake *FakeFalcoV1alpha1
}

var runtimeeventsResource = schema.GroupVersionResource{Group: "falco.appscode.com", Version: "v1alpha1", Resource: "runtimeevents"}

var runtimeeventsKind = schema.GroupVersionKind{Group: "falco.appscode.com", Version: "v1alpha1", Kind: "RuntimeEvent"}

// Get takes name of the runtimeEvent, and returns the corresponding runtimeEvent object, and an error if there is any.
func (c *FakeRuntimeEvents) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.RuntimeEvent, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(runtimeeventsResource, name), &v1alpha1.RuntimeEvent{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RuntimeEvent), err
}

// List takes label and field selectors, and returns the list of RuntimeEvents that match those selectors.
func (c *FakeRuntimeEvents) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.RuntimeEventList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(runtimeeventsResource, runtimeeventsKind, opts), &v1alpha1.RuntimeEventList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.RuntimeEventList{ListMeta: obj.(*v1alpha1.RuntimeEventList).ListMeta}
	for _, item := range obj.(*v1alpha1.RuntimeEventList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested runtimeEvents.
func (c *FakeRuntimeEvents) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(runtimeeventsResource, opts))
}

// Create takes the representation of a runtimeEvent and creates it.  Returns the server's representation of the runtimeEvent, and an error, if there is any.
func (c *FakeRuntimeEvents) Create(ctx context.Context, runtimeEvent *v1alpha1.RuntimeEvent, opts v1.CreateOptions) (result *v1alpha1.RuntimeEvent, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(runtimeeventsResource, runtimeEvent), &v1alpha1.RuntimeEvent{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RuntimeEvent), err
}

// Update takes the representation of a runtimeEvent and updates it. Returns the server's representation of the runtimeEvent, and an error, if there is any.
func (c *FakeRuntimeEvents) Update(ctx context.Context, runtimeEvent *v1alpha1.RuntimeEvent, opts v1.UpdateOptions) (result *v1alpha1.RuntimeEvent, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(runtimeeventsResource, runtimeEvent), &v1alpha1.RuntimeEvent{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RuntimeEvent), err
}

// Delete takes name of the runtimeEvent and deletes it. Returns an error if one occurs.
func (c *FakeRuntimeEvents) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(runtimeeventsResource, name, opts), &v1alpha1.RuntimeEvent{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeRuntimeEvents) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(runtimeeventsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.RuntimeEventList{})
	return err
}

// Patch applies the patch and returns the patched runtimeEvent.
func (c *FakeRuntimeEvents) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.RuntimeEvent, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(runtimeeventsResource, name, pt, data, subresources...), &v1alpha1.RuntimeEvent{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RuntimeEvent), err
}
