/*
Copyright AppsCode Inc. and Contributors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	falcov1alpha1 "kubeops.dev/falco-ui-server/apis/falco/v1alpha1"
	versioned "kubeops.dev/falco-ui-server/client/clientset/versioned"
	internalinterfaces "kubeops.dev/falco-ui-server/client/informers/externalversions/internalinterfaces"
	v1alpha1 "kubeops.dev/falco-ui-server/client/listers/falco/v1alpha1"
)

// RuntimeEventInformer provides access to a shared informer and lister for
// RuntimeEvents.
type RuntimeEventInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.RuntimeEventLister
}

type runtimeEventInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewRuntimeEventInformer constructs a new informer for RuntimeEvent type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewRuntimeEventInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredRuntimeEventInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredRuntimeEventInformer constructs a new informer for RuntimeEvent type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredRuntimeEventInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.FalcoV1alpha1().RuntimeEvents().List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.FalcoV1alpha1().RuntimeEvents().Watch(context.TODO(), options)
			},
		},
		&falcov1alpha1.RuntimeEvent{},
		resyncPeriod,
		indexers,
	)
}

func (f *runtimeEventInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredRuntimeEventInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *runtimeEventInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&falcov1alpha1.RuntimeEvent{}, f.defaultInformer)
}

func (f *runtimeEventInformer) Lister() v1alpha1.RuntimeEventLister {
	return v1alpha1.NewRuntimeEventLister(f.Informer().GetIndexer())
}
